name: SethLarney
favicon: null
layout_spectrum: 0.2927
typography_spectrum: 0.52679
title: Seth Larney. Award Winning Director.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ededed'
    - '#111015'
    - '#43423e'
    - '#838f8a'
    - '#84695d'
  brandStrength: 0
  lightness: 0.25
  saturation: 0.8125
  rhythmicContrast: 1
purpose: []
