name: SethLarney
favicon: null
layout_spectrum: 0.27294
typography_spectrum: 0.52679
title: 'Seth Larney. Film & TV Director. VFX Supervisor.'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ededed'
    - '#111015'
    - '#43423e'
    - '#838f8a'
    - '#84695d'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 0
purpose: []
