layout_spectrum: 0.7305494360625744
typography_spectrum: 0.7673833533190191
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.058063642820343375
  lightness: 0.027378149097785354
  saturation: 0.5740248621441424
  rhythmicContrast: 0.5950862406753004
name: Seth Larney
favicon: null
title: Seth Larney. Award Winning Director & VFX Supervisor
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
purpose: []
